### ISSUE TITLE
Logotype

### ISSUE THREAD

**Issue by zuurw** [openfun/arnold#116]
## Feature Request

Hi , my name is Zuur W. I'm a graphic designer and I'd like to collaborate on your open source project and propose free logo/icon design for your project. If it's something you're interested in, please, let me know!

Best Regards
Zuur

**Comment by jmaupetit** [comment]
Hi @zuurw :wave:

Thank you for this proposal! Yes: we would be pleased to work with you on a logotype for this project. 

First point: licensing. To make things perfectly clear: we would like to credit you for your work and be able to use your contribution in our communications (we are a public entity of the french government). I was thinking of a CC-BY-SA [2] or CC-BY-ND [3] license.

Second point: project/mission overview. We work in the Open Education field (MOOCs)

Third point: naming convention. We choose to name our projects with Happy Days TV Show characters [4], because it's... cool! Hence, potentially, you may decline your work in different flavors :wink: [5, 6, 7] 

Tell me what you think about those three points, and once again, thank you for this proposal :heart: 

References:

- [1] https://www.fun-mooc.fr
- [2] https://creativecommons.org/licenses/by-sa/4.0/
- [3] https://creativecommons.org/licenses/by-nd/4.0/
- [4] https://en.wikipedia.org/wiki/Happy_Days
- [5] https://github.com/openfun/richie
- [6] https://github.com/openfun/fonzie
- [7] https://github.com/openfun/marsha

**Comment by zuurw** [comment]
Hi @jmaupetit 

Good morning, thank you for all the information, so you have more than one project to work on? right?

My work is licensed under a Creative Commons Attribution 4.0 International License
https://creativecommons.org/licenses/by/4.0/

So I would like to know the first project I'm going to work on and know what you want. Should I start with Arnold?

Just tell me what you want

Best Regards

Zuur Willem

**Comment by jmaupetit** [comment]
CC-BY-4.0 is perfect! I think Richie is our most popular project at the moment, so let's go for it! Thx :heart:

**Comment by jmaupetit** [comment]
Hey @zuurw! I hope everything goes well. I just wanted to check with you that you are still motivated to work on a logotype for Arnold?

Please do not hesitate to tell us you won't have time for this. We would totally understand!

Best.
