### ISSUE TITLE
marsha not installable anymore

### ISSUE THREAD

**Issue by lunika** [openfun/arnold#180]
## Bug Report

**Expected behavior/code**

When I run init playbook with marsha app I expect no failure

**Actual Behavior**

Creating masha secrets fails whit this message:

```
TASK [Actually create the secrets in OpenShift] **********************************************************************************************************************************************
changed: [local] => (item=apps/marsha/templates/app/secret.yml.j2)
failed: [local] (item=apps/marsha/templates/app/secret_cloudfront_private_key.yml.j2) => {"changed": false, "error": 422, "item": "apps/marsha/templates/app/secret_cloudfront_private_key.yml.j2", "msg": "Failed to create object: Secret \"marsha-sshkey-73fcc8eea30738a6b9647f12a9e7ac8f877a64fa\" is invalid: data[%s][ssh-privatekey]: Required value"}
changed: [local] => (item=apps/marsha/templates/postgresql/secret.yml.j2)
```

**Steps to Reproduce**
1. Update your master branch
2. Run `./bin/bootstrap -e "apps_filter=marsha`

**Possible Solution**

Something was removed I think when we worked on creating vaults.

**Comment by sampaccoud** [comment]
My understanding is that in [apps/marsha/templates/app/secret_cloudfront_private_key.yml.j2](https://github.com/openfun/arnold/blob/master/apps/marsha/templates/app/secret_cloudfront_private_key.yml.j2), the variable `DJANGO_CLOUDFRONT_PRIVATE_KEY` is required (we default to '' and it doesn't work...).

Instead we should wrap the whole template in a {% if DJANGO_CLOUDFRONT_PRIVATE_KEY %} because it is not really required (Marsha can work without this key if `DJANGO_CLOUDFRONT_SIGNED_URLS_ACTIVE` is False ie signed urls is not activated).
