### ISSUE TITLE
Explanation needed for multi-node OpenShift cluster

### ISSUE THREAD

**Issue by suraj-goel** [openfun/arnold#345]
The documents does not clearly explain the deployment of openedX on a multi node cluster of openshift.
It would be a great help is someone can explain the procedure for deployment of openedX on multi node cluster.

**Comment by sampaccoud** [comment]
@suraj-goel As far as I understand, the number of nodes on your OpenShift cluster does not impact the way you deploy to it... At France Université Numérique, we run on several nodes and deploy with Arnold as it is here.

The only thing we do is configure the number of replicas of our pods according to the number of nodes we have in each cluster (see for example https://github.com/openfun/arnold/blob/master/apps/richie/templates/services/app/dc.yml.j2#L12), and configure the pod affinity (see https://github.com/openfun/arnold/blob/master/apps/richie/templates/services/app/dc.yml.j2#L23) so that each replica of a same pod runs on a different node as much as possible. This is important to achieve efficient redundancy of your pods.

**Comment by suraj-goel** [comment]
Okay,
I will try the configurations and deploy openedX platform on my multinode cluster.
Thanks.
